apiVersion: v1
kind: Service
metadata:
  name: ordenes-service
spec:
  selector:
    app: ordenes-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30082
  type: NodePort